name: Deploy Infrastructure

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install boto3 pytest

    - name: Run Python Tests
      env:
        PYTHONPATH: ${{ github.workspace }}
      run: pytest

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.6.6

    - name: Zip Lambda Function
      run: |
        cd visitor_lambda
        zip ../lambda.zip lambda_function.py

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        TF_VAR_s3_bucket_name: ${{ secrets.TF_VAR_s3_bucket_name }}
        TF_VAR_acm_certificate_arn: ${{ secrets.TF_VAR_acm_certificate_arn }}
